### PR TITLE
Psiphon and tor icon

### PR DESCRIPTION
**Pull request by hellais**

### CODE REVIEW

**Comment by hellais** [comment]
The CI is failing due to:
```
    Snapshot name: `Icons renders icon for Test Group 1`
```
I guess this is due to the fact that I updated the icons.

@sarathms how do I update the snapshots for the CI?

**Comment by sarathms** [comment]
````
yarn test -u
````
That updates the snapshot. I can dot it for this one.

**Comment by sarathms** [comment]
I updated the `Icons.test.js` test to render all icons like you did for the storybook. The snapshot will then keep track of all icons.

**Comment by sarathms** [comment]
Icons right now
image

**Pull request merged**
